### ISSUE TITLE
Number of questions that you need to fix

### ISSUE THREAD

**Issue by arani89** [Wings-Lab/Radio_identification_cnn#1]
1) Does it work with different powers of each transmitter?
2) Does it work if the same transmitters data is collected using different sensor?
3) Please do not hard-code the filenames. Use arguments with wildcards (such as file*).
4) How much time does training and testing require?

**Comment by nkulka** [comment]
1. I dont know it yet, but it should work.
2. It should work because the neural network extracts features of the transmitters, but we dont know it yet.
3. Ok in progress.
4. 1 hour for training on my machine. But I have been working with a fraction of data though, so I don't know the time for the whole 1 million datapoints.
